---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crusher
  namespace: crusher
spec:
  secretName: crusher-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - crusher.k8s.koobz.io
  renewBefore: 720h
