---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: crusher-database
  namespace: crusher
spec:
  storageClassName: minikube
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minikube
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate
